### PR TITLE
Bugfixes

### LINKED ISSUE #56: Changing tugs and barges hitbox height
All tugs and barges seem to adopt the hitbox height of the default boat. This means that trying to interact with them from the side will quite often fail, due the hitbox not covering the entire model. I would suggest altering the hitboxes height to allow users to interact with entities in the way they are used to.

### LINKED ISSUE #58: Way points > 200 blocks apart force path re-computation every tick
We should manually cache the path if the waypoint is too far, the navigator will only reuse the path properly if the target was reached in pathfinding, if it's too far and the path was estimated, the path will be recomputed resulting in very large performance impact.

This can be worked around by adding more waypoints to the route.

### PR DESCRIPTION
**Pull request by muradakh**
- Fix navigation performance (#58)
- Fix entity spring client de-sync
- Fix vessels propelling towards positive Z when underwater
- Fix fishing barge only checking one side for net deployment
- Improve hitbox positioning (#56) 

https://user-images.githubusercontent.com/31002977/152924846-841de3da-e7de-4bfb-813d-9de7d48fc8c1.mp4

### CODE REVIEW

**Comment by MuradAkh** [comment]
@EDToaster can you test this branch locally as well to make sure new navigation and sync is ok for you

**Review by EDToaster — COMMENTED** [review]
Reviewed, just going to do some testing first

**Comment by EDToaster** [comment]
Fixes #58, fixes #56

**Review by EDToaster — CHANGES_REQUESTED** [review]
Just need to fix the config

**Review by EDToaster — APPROVED** [review]

**Pull request merged**
