### PR TITLE
Created german translation

### PR DESCRIPTION
**Pull request by PrettyMuchTara**

### CODE REVIEW

**Comment by luaxlab** [comment]
Thanks for your contribution, however, there are some things I noted that may be changed:
- Some typos (e.g. 26, 42, 51)
- To literal translations (e.g. "Kistenkahn", also sounds a little weird - Maybe "Schute" is a better word?)
- A chunk may be referred to as "Region" or "Bereich".
- Energy is not current. The term "energy" refers to "electrified" in this context, thus "Elektrischer Schlepper" would be a better term I'd say.
- 44 sounds unnatural.
- I would poll for whether to use "barge" or "kahn" to refer to barges.

**Comment by PrettyMuchTara** [comment]
- Fixed typos at 26,42
- Changed capitalizaion of 51 (fix?)
- (checked on other translations of chunk loader in other mods, they were keeping the term chunk loader literaly, so no change)
- fixed. inital version used informal term for electric current/energy
- changed wording of 44. It's still a bit condensed but more fluent
- changed all descriptions of kahn to barge (more in line) except chest barge is now "schute" (more fitting for large scale inland goods transport ships)

**Comment by luaxlab** [comment]
Thank you, I'd all this good now.
Except, you may want to remove whitespaces from the names of the barge types (e.g. "Sitz Barge" -> "Sitzbarge")

**Comment by luaxlab** [comment]
Just noticed there is something wrong in 56

**Comment by MuradAkh** [comment]
@luaxlab @MrPeterman can you re-confirm that we are good to merge?

**Comment by luaxlab** [comment]
There is still something to be fixed in Line 56

**Comment by MuradAkh** [comment]
@MrPeterman could you address @luaxlab 's feedback.
Thanks!

**Comment by MuradAkh** [comment]
Closing this as the translations are outdated with 1.2 update. New PR would be certainly welcome!

**Pull request closed without merging**
