### PR TITLE
Create es_es.json

### PR DESCRIPTION
**Pull request by albertosaurio65**

### CODE REVIEW

**Comment by MuradAkh** [comment]
Hey could you rebase your branch on main-1.18 instead please, and PR against that branch.

Thanks a lot for help!

**Comment by albertosaurio65** [comment]
if i do that i can't create pull request

**Comment by MuradAkh** [comment]
You should be able to if you make changes on your own main-1.18 branch. We only use the release branch for actual releases, stuff should be merged into main-1.18

**Comment by albertosaurio65** [comment]
[es_es.zip](https://github.com/MuradAkh/LittleLogistics/files/8147423/es_es.zip)

It won't let me, I'll pass it to you manually

**Comment by EDToaster** [comment]
Convert to draft so we don't accidentally merge into 1.18-releases

**Review by muradakh — APPROVED** [review]

**Pull request merged**
